spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhujinfan/config-repo.git
          username: 1023846358@qq.com
          password: abc15855364086
          basedir: /develop/IntelliJIDEA2017.1.1/IdeaSpace/SpringCloud_SellA/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh